### ISSUE TITLE
Simualte only non constant ME's

### ISSUE THREAD

**Issue by diogenes1991** [diogenes1991/RBMSecar#1]
When the switch was made from 331 ME's to the full 495 to be able to catch any possible combination of powers, we got a performance hit of ~30%, this is likely because we are simulating a bunch of zeros.

We should only simulate non-constant ME's, the issue is to track these dynamical since in principle different magnets should have different constant ME's.

**Comment by eddbonilla** [comment]
I'm surprised about this, because if all we have are a bunch of zeros then the singular vectors should also have zero components in them, so the emulation should basically be the same. 

I think what you're suggesting is that we are currently limited by our ability to add matrices efficiently: 
330/495= 2/3. If this is the reason for the performance hit, then in means we are losing time in pure matrix operations of zeros. If that's the case, then that's incredible, because we can easily further parallelize some of the work if needed. 

In that case, I will agree with Diogenes that we might as well only simulate the nonzero elements and save that 30%. 

I will

**Comment by eddbonilla** [comment]
Another question for later: 

In practice, we will need to write these elements in a way that is useful for the 19-magnet analysis. If the time needed to recast the emulator into another format is way larger than the emulation time, then we should focus on lowering that latency instead.

**Comment by diogenes1991** [comment]
I think that it should be hidden, meaning that only the emulator should know about this difference, but things like the call function should still return the 495 matrix representation.
